### Import Packages

In [1]:
import json
import requests
from os import makedirs
from os.path import join, exists
from datetime import date, timedelta
import pandas as pd
import glob

### Create JSON Files

In [2]:

# ARTICLES_DIR = join('articles')
# makedirs(ARTICLES_DIR, exist_ok=True)

# API_ENDPOINT = 'http://content.guardianapis.com/search'
# my_params = {
#     'from-date': "",
#     'to-date': "",
#     'order-by': "newest",
#     'show-fields': 'all',
#     'page-size': 200,
#     'api-key': '6fb43cc2-9440-495f-a1a7-7d90af272fe0'
# }

# start_date = date(2021, 9, 1)
# end_date = date(2021,9, 30)
# dayrange = range((end_date - start_date).days + 1)
# for daycount in dayrange:
#     dt = start_date + timedelta(days=daycount)
#     datestr = dt.strftime('%Y-%m-%d')
#     fname = join(ARTICLES_DIR, datestr + '.json')
#     if not exists(fname):
#         # then let's download it
#         print("Downloading", datestr)
#         all_results = []
#         my_params['from-date'] = datestr
#         my_params['to-date'] = datestr
#         current_page = 1
#         total_pages = 1
#         while current_page <= total_pages:
#             print("...page", current_page)
#             my_params['page'] = current_page
#             resp = requests.get(API_ENDPOINT, my_params)
#             data = resp.json()
#             all_results.extend(data['response']['results'])
#             # if there is more than one page
#             current_page += 1
#             total_pages = data['response']['pages']

#         with open(fname, 'w') as f:
#             print("Writing to", fname)

#             # re-serialize it for pretty indentation
#             f.write(json.dumps(all_results, indent=2))

In [3]:
# a1 = pd.read_json(r'articles\2021-09-01.json')
# a1 = a1.fields
# a1 = a1.to_frame()

### Load JSON Files to DF

In [4]:

files = glob.glob('articles\*.json')

df=[]
for file in files:
    f = open(file, 'r')
    a1 = pd.read_json(f)
    a1 = a1.fields
    a1 = a1.to_frame()
    df = a1.append(df)

In [5]:
df = pd.DataFrame(df['fields'].values.tolist(), index=df.index).reset_index()

TypeError: list indices must be integers or slices, not str

In [ ]:
df

,index,headline,standfirst,trailText,byline,main,body,wordcount,firstPublicationDate,isInappropriateForSponsorship,...,commentable,newspaperEditionDate,scheduledPublicationDate,displayHint,liveBloggingNow,newspaperPageNumber,sensitive,starRating,allowUgc,contributorBio
0,0,‘Red wall’ Tories call on Rishi Sunak to cut b...,<p>MPs elected in former Labour heartlands in ...,MPs elected in former Labour heartlands in 201...,Jessica Elgot and Patrick Butler,"<figure class=""element element-image"" data-med...",<p>Conservative MPs in “red wall” seats have u...,625,2021-09-30T23:01:14Z,false,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"Home Office, Foreign Office and MoJ worst for ...",<p>Research into government transparency by le...,Research into government transparency by leadi...,Rajeev Syal,"<figure class=""element element-image"" data-med...","<p>The Home Office, the Foreign Office and the...",616,2021-09-30T23:01:13Z,false,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"Cryptic crossword No 28,565",NaN,"Cryptic crossword No 28,565",Pasquale,,,0,2021-09-30T23:00:13Z,false,...,true,2021-10-01T00:00:00Z,2021-09-30T23:00:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Premier League: 10 things to look out for this...,"<p>Manchester City head for Anfield, how best ...","Manchester City head for Anfield, how best for...","Nick Ames, Will Unwin and Daniel Harris","<figure class=""element element-image element--...",<h2>1) City need to end striking questions</h2...,1752,2021-09-30T23:00:06Z,false,...,true,NaN,NaN,immersive,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"UK reports 36,480 new cases – as it happened",<p>Thanks for following along – this blog is n...,Thanks for following along – this blog is now ...,"Jane Clinton (now); Kaamil Ahmed, Tom Ambrose ...","<figure class=""element element-image"" data-med...","<div id=""block-615637968f08879300dabb19"" class...",8063,2021-09-30T04:17:46Z,false,...,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6542,217,US Open 2021: Novak Djokovic defeats Holger Vi...,"<ul><li>Djokovic wins 6-1, 5-7, 6-2, 6-1 to la...",<strong>As it happened:</strong> Top seeds Ash...,Bryan Armen Graham at Flushing Meadows,"<figure class=""element element-image"" data-med...","<div id=""block-612ed9fb8f08bf4765a41d40"" class...",5240,2021-08-31T17:30:04Z,false,...,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,NaN
6543,218,The latest Covid lockdowns have locked Austral...,<p>Boosting payments and scrapping perverse el...,Boosting payments and scrapping perverse eligi...,"Jay Coonan, Kristin O’Connell and Jeremy Poxon","<figure class=""element element-image"" data-med...",<p>As Sydney smashes daily Covid case records ...,897,2021-09-01T01:32:49Z,false,...,true,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6544,219,Israel reports record daily Covid cases – as i...,"<p>This blog is now closed. See <a href=""https...",This blog is now closed. See all our coronavir...,"Nadeem Badshah (now) and Alex Mistlin, Tom Amb...","<figure class=""element element-image"" data-med...","<div id=""block-612ec5078f08bf4765a41c88"" class...",8712,2021-08-31T05:07:23Z,false,...,true,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,NaN
6545,220,Biden declares ‘it was time to end this war’ i...,"<ul><li><a href=""https://www.theguardian.com/u...",President says US was ready for ‘every eventua...,"Maanvi Singh (now), Joanna Walters and Lauren ...","<figure class=""element element-atom""> \n <gu-a...","<div id=""block-612ebd688f083528f0f504fc"" class...",7035,2021-08-31T13:25:49Z,false,...,NaN,NaN,NaN,NaN,false,NaN,NaN,NaN,NaN,NaN
6546,221,"Portable, seasonal, wonderful: 10 Yotam Ottole...","<p>As the last vestiges of winter fall away, g...","As the last vestiges of winter fall away, grab...",Kate Waldegrave,"<figure class=""element element-image"" data-med...","<p>Before you panic-buy olives, dips and an un...",790,2021-09-01T00:00:15Z,false,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Export Data to CSV

In [ ]:
df_reg = df.copy(deep=True)


df_reg['body'] = df_reg['body'].str.replace(r'<[^<>]*>', '', regex=True)

In [ ]:
txt = df['body']

In [ ]:
txt = pd.DataFrame(txt)

In [ ]:
# txt.to_csv('out.txt', index=False)
compression_opts = dict(method='zip',
                        archive_name='out2.csv')  
txt.to_csv('out2.zip', index=False,
          compression=compression_opts)